USE [master]
GO

/****** Object:  Database [Crash]    Script Date: 12/11/2014 17:21:12 ******/
CREATE DATABASE [Crash] ON  PRIMARY 
( NAME = N'Crash', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\Crash.mdf' , SIZE = 2048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Crash_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\Crash_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Crash] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Crash].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Crash] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Crash] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Crash] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Crash] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Crash] SET ARITHABORT OFF 
GO

ALTER DATABASE [Crash] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Crash] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Crash] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Crash] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Crash] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Crash] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Crash] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Crash] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Crash] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Crash] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Crash] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Crash] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Crash] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Crash] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Crash] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Crash] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Crash] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Crash] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Crash] SET  READ_WRITE 
GO

ALTER DATABASE [Crash] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Crash] SET  MULTI_USER 
GO

ALTER DATABASE [Crash] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Crash] SET DB_CHAINING OFF 
GO


